---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install REPO EPEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: ansible_facts['os_family'] == "RedHat"


- name: Install MariaDB package (Redhat)
  dnf: 
    name: 
      - mariadb-server
      - python3-mysql
    state: present
  when: ansible_facts['os_family'] == "RedHat"


- name: Install MariaDB package (Debian)
  apt: 
    name: "{{ item }}" 
    state: present
  with_items:
   - mariadb-server
   - MySQL-python
  when: ansible_facts['os_family'] == "Debian"

- name: Configure SELinux to start mysql on any port
  seboolean: 
    name: mysql_connect_any 
    state: true 
    persistent: yes

- name: Create Mysql configuration file
  template: 
   src: my.cnf.j2 
   dest: /etc/my.cnf
   mode: 0755
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: 
    path: /var/log/mysqld.log 
    state: touch 
    owner: mysql 
    group: mysql 
    mode: 0775

- name: Create MariaDB PID directory
  file: 
    path: /var/run/mysqld 
    state: directory 
    owner: mysql 
    group: mysql 
    mode: 0775

- name: Start MariaDB Service
  service: 
    name: mariadb 
    state: started 
    enabled: yes

- name: Start firewalld
  service: 
    name: firewalld 
    state: started 
    enabled: yes

- name: insert firewalld rule
  firewalld: 
    port: "{{ mysql_port }}/tcp" 
    permanent: true 
    state: enabled 
    immediate: yes

- name: Create Application Database
  mysql_db: 
   name: "{{ dbname }}" 
   state: present

- name: Create Application DB User
  mysql_user:
    name: "{{ dbuser }}" 
    password: "{{ upassword }}" 
    priv: "*.*:ALL" 
    host: '%' 
    state: present
